In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [3]:
datasets = load_iris()
x, y = datasets.data, datasets.target

In [4]:
model = SVC(kernel='linear', C=1)
model.fit(x, y)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

model.score(x_test, y_test)

y_pred= model.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 1)

model.score(x_test, y_test)

y_pred= model.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

1.0

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        20

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60



In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[19  0  0]
 [ 0 21  0]
 [ 0  0 20]]


In [18]:
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_test, y_pred)

1.0

In [19]:
from sklearn.metrics import homogeneity_score
print(homogeneity_score(y_test, y_pred))

1.0


In [20]:
from sklearn.metrics import v_measure_score
print(v_measure_score(y_test, y_pred))

1.0


In [25]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_gamma_deviance
from sklearn.metrics import mean_poisson_deviance
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import mean_tweedie_deviance
from sklearn.metrics import r2_score

In [26]:
print('mean_absolute_error :', mean_absolute_error(y_test, y_pred))
#print('mean_gamma_deviance: ', mean_gamma_deviance(y_test, y_pred))
#print('mean_poisson_deviance: ', mean_poisson_deviance(y_test, y_pred))
print('mean_squared_error: ', mean_squared_error(y_test, y_pred))
print('mean_squared_log_error: ', mean_squared_log_error(y_test, y_pred))
print('mean_tweedie_deviance: ',mean_tweedie_deviance(y_test, y_pred))
print('r2_score: ',r2_score(y_test, y_pred))

mean_absolute_error : 0.0
mean_squared_error:  0.0
mean_squared_log_error:  0.0
mean_tweedie_deviance:  0.0
r2_score:  1.0


In [28]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

In [29]:
logistic = LogisticRegression()

In [43]:
penalty = ['l1','l2']
c = np.logspace(0, 4, 10)
hyperperameters = dict(C = c, penalty = penalty)